# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: jpfhir.jp.fhir.core.terminology.JFAGY
canonical: http://jpfhir.jp/fhir/core/terminology/JFAGY
name: JFAGY
title: "J-FAGYアレルゲンコード"
description: "J-FAGYアレルゲンコード"
status: active # draft | active | retired | unknown
version: "2025.02.07"
date: 2025-02-07
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: release
#license: CC-BY4.0
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: 国立大学法人東京大学（大学院医学系研究科医療情報学分野）
  url: https://jpfhir.jp/fhir/core/terminology/JFAGY/
  email: office@jpfhir.jp
copyright: 国立大学法人東京大学、（一社）日本医療情報学会 CC BY-ND 4.0 （クリエイティブ・コモンズ 表示-改変禁止 4.0 国際 パブリック・ライセンス）
jurisdiction: 'urn:iso:std:iso:3166#JP'
#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: JFAGY
  download.md:
    title: CSV・Excelダウンロード
  history.md:
    title: 改訂履歴
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
  Artifacts: 
    Artifacts: artifacts.html
  ダウンロード:
    CSV・Excelページ: download.html
  改訂履歴: history.html
    
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
  path-expansion-params: '../../input/_resources/exp-params.json'
  active-tables: 'false'
  apply-version: 'false'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'false'
  generate:
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
  special-url:
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagyFoodAllergen_CS
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagyNonFoodNonMedicationAllergen_CS
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagySpecialCode_CS
    - http://jpfhir.jp/fhir/core/ValueSet/JP_AllergyIntolerance_VS
  
  